apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "console-oauth2proxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "console-oauth2proxy.labels" . | nindent 4 }}