apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: console
    {{- include "console.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: console
    {{- include "console.selectorLabels" . | nindent 4 }}
