apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "console.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
secrets:
  - name: {{ include "console.serviceAccountName" . }}
automountServiceAccountToken: false

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "console.serviceAccountName" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "console.serviceAccountName" . }}
type: kubernetes.io/service-account-token
