apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  traefik.yml: |
    http:
      serversTransports:
        insecure:
          insecureSkipVerify: true
        tmaxcloud:
          serverName: tmax-cloud
          rootCAs:
            - /var/run/secrets/tmaxcloud/ca.crt
        kubernetes:
          rootCAs:
            - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      middlewares:
        cors-header:
          headers:
            accessControlAllowMethods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
            ## https://github.com/traefik/traefik/issues/8961
            accessControlAllowHeaders: [ "Accept", "Authorization", "Content-Type", "Origin" ]
{{- if .Values.tls.domain }}
            accessControlAllowOriginListRegex:
              - "([a-z]+)\\.{{ (split "." .Values.tls.domain)._0 }}\\.{{ (split "." .Values.tls.domain)._1 }}"
{{- end }}
            accessControlMaxAge: 100
            addVaryHeader: true
            # Add for sending a request with credentials (cookie)
            accessControlAllowCredentials: true
        hypercloud-stripprefix:
          stripPrefix:
            prefixes:
              - "/api/hypercloud"
              - "/api/multi-hypercloud"
              - "/api/webhook"
        kubernetes-stripprefix:
          stripPrefix:
            prefixes:
              - "/api/kubernetes"
            forceSlash: true
        monitoring-stripprefix:
          stripPrefix:
            prefixes:
              - "/api/prometheus"
              - "/api/alertmanager"
        monitoring-stripprefix-tenancy:
          stripPrefix:
            prefixes:
              - "/api/prometheus-tenancy"
