{{- if .Values.tls.acme.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  name: route53-secret
type: Opaque
data:
  secret_access_key: {{ .Values.tls.acme.dns.accessKeySecret | b64enc }}
{{- end }}
