{{- if .Values.tls.acme.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  defaultCertificate:
    secretName: {{ .Values.tls.acme.dns.type }}-acme-crt-secret
{{- end }}

{{- if .Values.tls.selfsigned.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  defaultCertificate:
    secretName: selfsigned-crt-secret
{{- end }}