apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  name: insecure
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  name: tmaxcloud
spec:
  serverName: tmax-cloud
  rootCAsSecrets:
    - selfsigned-ca
---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  name: kubernetes
spec:
  rootCAsSecrets:
    - {{ .Values.traefik.fullnameOverride }}
