apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default "api-gateway-system" }}
  labels:
    {{- include "namespace.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-1"