apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccount }}
  labels:
    {{- include "addons.labels" . | nindent 4 }}
secrets:
  - name: {{ .Values.global.serviceAccount }}
automountServiceAccountToken: false

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.serviceAccount }}
  labels:
    {{- include "addons.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.global.serviceAccount }}
type: kubernetes.io/service-account-token
