apiVersion: v2
appVersion: 7.3.0
dependencies:
- alias: redis
  condition: redis.enabled
  name: redis
  repository: file://charts/redis
  version: 16.4.5
description: A reverse proxy that provides authentication with Google, Github or other providers
home: https://tmax-cloud.github.io/charts/
kubeVersion: '>=1.9.0-0'
name: oauth2-proxy
sources:
- https://github.com/oauth2-proxy/oauth2-proxy
- https://github.com/oauth2-proxy/manifests
version: 6.2.2
