tls:
  domain: ""
  acme:
    enabled: false
    email: "temp@tmax.co.kr"
    dns:
      type: route53
      accessKeyID: accessKeyID
      accessKeySecret: accessKeySecret
      hostedZoneID: hostZoneID
    # staging or production
    environment: staging
  selfsigned:
    enabled: true

## crd 선행 설치
## kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.crds.yaml
cert-manager:
  enabled: false
  fullnameOverride: cert-manager
  extraArgs:
    - "--dns01-recursive-nameservers=8.8.8.8:53"
    - "--dns01-recursive-nameservers-only"
    - "--enable-certificate-owner-ref"
#  image:
#    repository: imageRepository
#  cainjector:
#    image:
#      repository: imageRepository
#  webhook:
#    image:
#      repository: imageRepository
## 파드에 imagePullSecrets 이 없는 경우, ServiceAccount 의 imagePullSecrets 이 파드에 추가된다
## https://kubernetes.io/ko/docs/reference/access-authn-authz/service-accounts-admin/
#  global:
#    imagePullSecrets:
#      - name: regcred
#  resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi
#  cainjector:
#    resources:
#      requests:
#        cpu: 100m
#        memory: 128Mi
#  webhook:
#    resources:
#      requests:
#        cpu: 100m
#        memory: 128Mi

traefik:
  enabled: true
  fullnameOverride: traefik
  additionalArguments:
    - "--serverstransport.rootcas=/var/run/secrets/tmaxcloud/ca.crt,/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    - "--entrypoints.websecure.http.middlewares=cors-header@file"
    - "--providers.file"
    - "--providers.file.directory=/gateway-config"
    - "--providers.file.watch=true"
    # Only use dev environment
    #    - "--serverstransport.insecureskipverify=true"
  image:
    name: traefik
    tag: "v2.8.0"
  deployment:
    podLabels:
      app: traefik
    imagePullSecrets: []
    #  imagePullSecrets:
    #    - name: regcred
  volumes:
    - name: gateway-config
      mountPath: "/gateway-config"
      type: configMap
    - name: selfsigned-ca
      mountPath: "/var/run/secrets/tmaxcloud"
      type: secret
  service:
    # LoadBalancer , NodePort, ClusterIP
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
#  env: []
  env:
    - name: TZ
      value: Asia/Seoul
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: Exists

  # Create an IngressRoute for the dashboard
  ingressRoute:
    dashboard:
      enabled: false
      # Additional ingressRoute annotations (e.g. for kubernetes.io/ingress.class)
      annotations: {}
      # Additional ingressRoute labels (e.g. for filtering IngressRoute by custom labels)
      labels: {}
      # optional: dashboard login id
      id: ""
      # optional: dashboard login password
      password: ""

