{{- if .Values.modules.gatewayBootstrap.traefik.enabled }}
{{ $isMaster := eq .Values.global.cluster "master" }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "gateway-bootstrap-gateway" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  name: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 3
      backoff:
        duration: "30s"
        factor: 2
        maxDuration: "3m0s"
  destination:
    server: {{ .Values.global.clusterName }}
    namespace: api-gateway-system
  project: {{ .Values.spec.project }}
  source:
    path: gateway
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: gateway
      parameters:
      {{- with .Values.modules.gatewayBootstrap.tls }}
      {{- if .acme.enabled }}
        - name: tls.acme.enabled
          value: "true"
        - name: tls.acme.email
          value: {{ .acme.email }}
        - name: tls.acme.dns.accessKeyID
          value: {{ .acme.dns.accessKeyID }}
        - name: tls.acme.dns.accessKeySecret
          value: {{ .acme.dns.accessKeySecret }}
        - name: tls.acme.dns.hostedZoneID
          value: {{ .acme.dns.hostedZoneID }}
        - name: tls.domain
          value: {{ $.Values.global.domain }}
        - name: tls.selfsigned.enabled
          value: "false"
      {{- else if .selfsigned.enabled }}
        - name: tls.selfsigned.enabled
          value: "true"
        - name: tls.domain
          value: {{ $.Values.global.domain }}
        - name: tls.acme.enabled
          value: "false"
      {{- else }}
        - name: tls.selfsigned.enabled
          value: "false"
        - name: tls.acme.enabled
          value: "false"
      {{- end }}
      {{- end }}
      {{- if not (eq .Values.global.timeZone "UTC") }}
        - name: traefik.env[0].name
          value: TZ
        - name: traefik.env[0].value
          value: {{ .Values.global.timeZone }}
      {{- end }}
      {{- if .Values.modules.gatewayBootstrap.certManager.enabled }}
        - name: certmanager.enabled
          value: {{ .Values.modules.gatewayBootstrap.certManager.enabled | quote }}
      {{- end }}
      {{- if.Values.global.privateRegistry }}
        - name: traefik.image.name
          value: {{ .Values.global.privateRegistry }}/docker.io/library/traefik
        {{- if .Values.modules.gatewayBootstrap.certManager.enabled }}
        - name: certmanager.image.repository
          value: "{{ .Values.global.privateRegistry }}/quay.io/jetstack/cert-manager-controller"
        - name: certmanager.cainjector.image.repository
          value: "{{ .Values.global.privateRegistry }}/quay.io/jetstack/cert-manager-cainjector"
        - name: certmanager.webhook.image.repository
          value: "{{ .Values.global.privateRegistry }}/quay.io/jetstack/cert-manager-webhook"
        - name: certmanager.startupapicheck.image.repository
          value: "{{ .Values.global.privateRegistry }}/quay.io/jetstack/cert-manager-ctl"
        {{- end }}
      {{- end }}
{{- end }}
