apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 1
      backoff:
        duration: "10s"
        factor: 2
        maxDuration: "1m0s"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: api-gateway-system
  project: default
  source:
    path: console
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: console
      valueFiles:
        - teams/local-test.yaml