apiVersion: v2
appVersion: 1.15.4
description: Helm chart for deploying Istio gateways
keywords:
- istio
- gateways
name: gateway
sources:
- http://github.com/istio/istio
type: application
version: 1.15.4
