{{- if .Values.tls.selfsigned.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  name: selfsigned-crt
spec:
  secretName: selfsigned-crt-secret
  commonName: {{ .Values.tls.domain }}
  subject:
    organizations:
      - "tmax-cloud"
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - "tmax-cloud"
    - {{ .Values.tls.domain | quote }}
    - {{ printf "*.%s" .Values.tls.domain | quote }}
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: tmaxcloud-issuer
{{- end }}