kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "jwt-decode-auth.fullname" . }}
  labels:
  {{- include "jwt-decode-auth.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "jwt-decode-auth.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "jwt-decode-auth.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}