apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jwt-decode-auth.fullname" . }}
  labels:
    {{- include "jwt-decode-auth.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jwt-decode-auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jwt-decode-auth.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: jwt-token
          secret:
            defaultMode: 420
            secretName: {{ template "jwt-decode-auth.serviceAccountName" . }}
{{- if .Values.timeZone }}
{{- if not (eq .Values.timeZone "UTC") }}
        - name: timezone-config
          hostPath:
            path: "/usr/share/zoneinfo/{{ .Values.timeZone }}"
{{- end }}
{{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: JWKS_URL
              value: "https://{{ .Values.hyperAuth.address }}/auth/realms/{{ .Values.hyperAuth.realm }}/protocol/openid-connect/certs"
            - name: AUTH_HEADER_KEY
              value: Authorization
            - name: CACHE_ENABLED
              value: "true"
            - name: LOG_LEVEL
              value: {{ .Values.logInfo.logLevel }}
            - name: LOG_TYPE
              value: {{ .Values.logInfo.logType }}
            - name: MAX_CACHE_KEYS
              value: "10000"
            - name: PORT
              value: "8080"
            - name: TOKEN_VALIDATED_HEADER_KEY
              value: jwt-token-validated
            - name: MULTI_CLUSTER_PREFIX
              value: multicluster
          volumeMounts:
{{- if .Values.timeZone }}
{{- if not (eq .Values.timeZone "UTC") }}
            - mountPath: /etc/localtime
              name: timezone-config
{{- end }}
{{- end }}
            - name: jwt-token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
              path: /ping
          readinessProbe:
            httpGet:
              port: http
              path: /ping
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}