apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jwt-decode-auth.serviceAccountName" . }}
  labels:
    {{- include "jwt-decode-auth.labels" . | nindent 4 }}
secrets:
  - name: {{ template "jwt-decode-auth.serviceAccountName" . }}
automountServiceAccountToken: false

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jwt-decode-auth.serviceAccountName" . }}
  labels:
    {{- include "jwt-decode-auth.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ template "jwt-decode-auth.serviceAccountName" . }}
type: kubernetes.io/service-account-token
