{{- if .Values.modules.certManager.enabled }}
{{ $isMaster := eq .Values.global.cluster "master" }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "cert-manager" }}
{{ $ns := "ns-cert-manager" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  {{- include "apps.labels" . | nindent 4 }}
  name: {{ ternary $ns (printf "%s-%s" $prefix $ns) $isMaster }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true
      prune: true
  destination:
    name: {{ .Values.global.clusterName }}
  project: {{ .Values.spec.project }}
  source:
    path: charts/namespace
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: namespace
      parameters:
        - name: namespace
          value: cert-manager
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  {{- include "apps.labels" . | nindent 4 }}
  name: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 3
      backoff:
        duration: "30s"
        factor: 2
        maxDuration: "3m0s"
  destination:
    name: {{ .Values.global.clusterName }}
    namespace: api-gateway-system
  project: {{ .Values.spec.project }}
  source:
    path: charts/gateway
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: cert-manager
      valueFiles:
        - values.yaml
      {{- if .Values.global.privateRegistry }}
      parameters:
        - name: certManager.image.repository
          value: "{{ .Values.global.privateRegistry }}/quay.io/jetstack/cert-manager-controller"
        - name: certManager.cainjector.image.repository
          value: "{{ .Values.global.privateRegistry }}/quay.io/jetstack/cert-manager-cainjector"
        - name: certManager.webhook.image.repository
          value: "{{ .Values.global.privateRegistry }}/quay.io/jetstack/cert-manager-webhook"
        - name: certManager.startupapicheck.image.repository
          value: "{{ .Values.global.privateRegistry }}/quay.io/jetstack/cert-manager-ctl"
      {{- end }}
---
{{- end }}