apiVersion: v2
appVersion: 116.0
name: console
description: A console with oauth2-proxy and jwt-decode
home: https://github.com/tmax-cloud/console
dependencies:
  - name: oauth2-proxy
    version: 6.2.2
    repository: https://oauth2-proxy.github.io/manifests
    alias: oauth2-proxy
    condition: oauth2Proxy.enabled
  - name: jwt-decode-auth
    version: 1.0.0
    repository: file://charts/jwt-decode-auth
    alias: jwt-decode-auth
    condition: jwtDecodeAuth.enabled
sources:
  - https://github.com/tmax-cloud/console
version: 0.2.0
