# Default values for console.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  serviceAccount: console

nameOverride: "console"
fullnameOverride: "console"

console:
  auth:
    hyperAuth: hyperauth.tmaxcloud.org
    realm: tmax
    clientId: hypercloud5
  mcMode: true
  chatbotEmbed: true
  logInfo:
    logLevel: "debug"
    logType: "pretty"
  ingressroute:
    enabled: true
    domain:
      enabled: true
      host: ck1-1.link
    ip:
      enabled: false

oauth2-proxy:
  enabled: true
  fullnameOverride: "oauth2-proxy"
  config:
    redirectUrl: "https://console.ck1-1.link/oauth2/callback"
  ingressroute:
    enabled: true
    host: ck1-1.link

jwt-decode-auth:
  enabled: true
  fullnameOverride: "jwt-decode-auth"
  hyperauth:
    address: hyperauth.tmaxcloud.org
    realm: tmax
  logInfo:
    logLevel: "debug"
    logType: "pretty"


service:
  type: ClusterIP
  port: 31303


image:
  repository: docker.io/tmaxcloudck/hypercloud-console
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "oauth"
#  tag: "5.0.78.0"
imagePullSecrets: []
#imagePullSecrets:
#  - name: regcred

#nodeSelector:
#  node-role.kubernetes.io/master: ""

#tolerations: []
tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: Exists

affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - traefik
        weight: 100

replicaCount: 1

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

podAnnotations: {}
podSecurityContext:
  {}
  # fsGroup: 2000
securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

