apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "helm-namespace-config.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-1"